name: Get Inventory
description: Get inventory description
inputs:
  token:
    description: secrets Pat
    required: true
runs:
  using: composite
  steps:
    - name: Checkout srw241/mock repo
      uses: actions/checkout@v3
      with:
        repository: srw241/mock
        ref: main
        path: inventory
        token: ${{ inputs.token }}
    
    - name: Copy ansible-inventory.yml and group_vars to repo workspace
      run: |
        cp ./inventory/ansible-inventory.yml $(pwd)
        cp -R ./inventory/group_vars $(pwd)
        rm -rf ./inventory
        ls $(pwd)
      shell: bash