name: Get Inventory
description: Get inventory description
inputs:
  token:
    description: secrets Pat
    required: true
runs:
  using: composite
  steps:
    - name: Checkout srw241/mock repo
      uses: actions/checkout@v3
      with:
        repository: srw241/mock
        ref: main
        path: inventory
        token: ${{ inputs.token }}